package com.swust.kelab.domain;

import java.util.Date;

public class GroupPaperParameter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_questionType
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaQuestiontype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaDifficulty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_questionScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float gppaQuestionscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_questionNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaQuestionnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String gppaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date gppaCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_creatorId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaCreatorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column GroupPaperParameter.gppa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gppaOrdinal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_id
	 * @return  the value of GroupPaperParameter.gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaId() {
		return gppaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_id
	 * @param gppaId  the value for GroupPaperParameter.gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaId(Integer gppaId) {
		this.gppaId = gppaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_questionType
	 * @return  the value of GroupPaperParameter.gppa_questionType
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaQuestiontype() {
		return gppaQuestiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_questionType
	 * @param gppaQuestiontype  the value for GroupPaperParameter.gppa_questionType
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaQuestiontype(Integer gppaQuestiontype) {
		this.gppaQuestiontype = gppaQuestiontype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_difficulty
	 * @return  the value of GroupPaperParameter.gppa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaDifficulty() {
		return gppaDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_difficulty
	 * @param gppaDifficulty  the value for GroupPaperParameter.gppa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaDifficulty(Integer gppaDifficulty) {
		this.gppaDifficulty = gppaDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_questionScore
	 * @return  the value of GroupPaperParameter.gppa_questionScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getGppaQuestionscore() {
		return gppaQuestionscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_questionScore
	 * @param gppaQuestionscore  the value for GroupPaperParameter.gppa_questionScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaQuestionscore(Float gppaQuestionscore) {
		this.gppaQuestionscore = gppaQuestionscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_questionNum
	 * @return  the value of GroupPaperParameter.gppa_questionNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaQuestionnum() {
		return gppaQuestionnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_questionNum
	 * @param gppaQuestionnum  the value for GroupPaperParameter.gppa_questionNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaQuestionnum(Integer gppaQuestionnum) {
		this.gppaQuestionnum = gppaQuestionnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_name
	 * @return  the value of GroupPaperParameter.gppa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getGppaName() {
		return gppaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_name
	 * @param gppaName  the value for GroupPaperParameter.gppa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaName(String gppaName) {
		this.gppaName = gppaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_createTime
	 * @return  the value of GroupPaperParameter.gppa_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getGppaCreatetime() {
		return gppaCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_createTime
	 * @param gppaCreatetime  the value for GroupPaperParameter.gppa_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaCreatetime(Date gppaCreatetime) {
		this.gppaCreatetime = gppaCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_creatorId
	 * @return  the value of GroupPaperParameter.gppa_creatorId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaCreatorid() {
		return gppaCreatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_creatorId
	 * @param gppaCreatorid  the value for GroupPaperParameter.gppa_creatorId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaCreatorid(Integer gppaCreatorid) {
		this.gppaCreatorid = gppaCreatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column GroupPaperParameter.gppa_ordinal
	 * @return  the value of GroupPaperParameter.gppa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGppaOrdinal() {
		return gppaOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column GroupPaperParameter.gppa_ordinal
	 * @param gppaOrdinal  the value for GroupPaperParameter.gppa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGppaOrdinal(Integer gppaOrdinal) {
		this.gppaOrdinal = gppaOrdinal;
	}
}