package com.swust.kelab.domain;

import java.util.Date;

public class NoticeAnnouncement {
	
	public NoticeAnnouncement() {}

	public NoticeAnnouncement(NoticeAnnouncement notice) {
		this.noanId = notice.noanId;
		this.noanTitle = notice.noanTitle;
		this.noanRoleids = notice.noanRoleids;
		this.noanPubtime = notice.noanPubtime;
		this.noanTopdays = notice.noanTopdays;
		this.noanIsimport = notice.noanIsimport;
		this.noanViewnum = notice.noanViewnum;
		this.noanAttachment = notice.noanAttachment;
		this.noanCreatorid = notice.noanCreatorid;
		this.noanContent = notice.noanContent;
		this.noanDeparid = notice.noanDeparid;
		this.noanCourid = notice.noanCourid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer noanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String noanTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_roleids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String noanRoleids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date noanPubtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_topdays
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer noanTopdays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_isimport
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean noanIsimport;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_viewnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer noanViewnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean noanAttachment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_creatorid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer noanCreatorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NoticeAnnouncement.noan_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String noanContent;
	
	/**	部门id	**/
	private Integer noanDeparid;
	
	/**	课程id	**/
	private Integer noanCourid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_id
	 * @return  the value of NoticeAnnouncement.noan_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getNoanId() {
		return noanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_id
	 * @param noanId  the value for NoticeAnnouncement.noan_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanId(Integer noanId) {
		this.noanId = noanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_title
	 * @return  the value of NoticeAnnouncement.noan_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getNoanTitle() {
		return noanTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_title
	 * @param noanTitle  the value for NoticeAnnouncement.noan_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanTitle(String noanTitle) {
		this.noanTitle = noanTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_roleids
	 * @return  the value of NoticeAnnouncement.noan_roleids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getNoanRoleids() {
		return noanRoleids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_roleids
	 * @param noanRoleids  the value for NoticeAnnouncement.noan_roleids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanRoleids(String noanRoleids) {
		this.noanRoleids = noanRoleids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_pubtime
	 * @return  the value of NoticeAnnouncement.noan_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getNoanPubtime() {
		return noanPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_pubtime
	 * @param noanPubtime  the value for NoticeAnnouncement.noan_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanPubtime(Date noanPubtime) {
		this.noanPubtime = noanPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_topdays
	 * @return  the value of NoticeAnnouncement.noan_topdays
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getNoanTopdays() {
		return noanTopdays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_topdays
	 * @param noanTopdays  the value for NoticeAnnouncement.noan_topdays
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanTopdays(Integer noanTopdays) {
		this.noanTopdays = noanTopdays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_isimport
	 * @return  the value of NoticeAnnouncement.noan_isimport
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getNoanIsimport() {
		return noanIsimport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_isimport
	 * @param noanIsimport  the value for NoticeAnnouncement.noan_isimport
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanIsimport(Boolean noanIsimport) {
		this.noanIsimport = noanIsimport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_viewnum
	 * @return  the value of NoticeAnnouncement.noan_viewnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getNoanViewnum() {
		return noanViewnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_viewnum
	 * @param noanViewnum  the value for NoticeAnnouncement.noan_viewnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanViewnum(Integer noanViewnum) {
		this.noanViewnum = noanViewnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_attachment
	 * @return  the value of NoticeAnnouncement.noan_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getNoanAttachment() {
		return noanAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_attachment
	 * @param noanAttachment  the value for NoticeAnnouncement.noan_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanAttachment(Boolean noanAttachment) {
		this.noanAttachment = noanAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_creatorid
	 * @return  the value of NoticeAnnouncement.noan_creatorid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getNoanCreatorid() {
		return noanCreatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_creatorid
	 * @param noanCreatorid  the value for NoticeAnnouncement.noan_creatorid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanCreatorid(Integer noanCreatorid) {
		this.noanCreatorid = noanCreatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NoticeAnnouncement.noan_content
	 * @return  the value of NoticeAnnouncement.noan_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getNoanContent() {
		return noanContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NoticeAnnouncement.noan_content
	 * @param noanContent  the value for NoticeAnnouncement.noan_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setNoanContent(String noanContent) {
		this.noanContent = noanContent;
	}

	public Integer getNoanDeparid() {
		return noanDeparid;
	}

	public void setNoanDeparid(Integer noanDeparid) {
		this.noanDeparid = noanDeparid;
	}

	public Integer getNoanCourid() {
		return noanCourid;
	}

	public void setNoanCourid(Integer noanCourid) {
		this.noanCourid = noanCourid;
	}
}