package com.swust.kelab.domain;

public class Action {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action.acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer actiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action.acti_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String actiName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action.acti_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String actiUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action.acti_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer actiType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Action.acti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String actiDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action.acti_id
	 * @return  the value of Action.acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getActiId() {
		return actiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action.acti_id
	 * @param actiId  the value for Action.acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setActiId(Integer actiId) {
		this.actiId = actiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action.acti_name
	 * @return  the value of Action.acti_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getActiName() {
		return actiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action.acti_name
	 * @param actiName  the value for Action.acti_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setActiName(String actiName) {
		this.actiName = actiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action.acti_url
	 * @return  the value of Action.acti_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getActiUrl() {
		return actiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action.acti_url
	 * @param actiUrl  the value for Action.acti_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setActiUrl(String actiUrl) {
		this.actiUrl = actiUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action.acti_type
	 * @return  the value of Action.acti_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getActiType() {
		return actiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action.acti_type
	 * @param actiType  the value for Action.acti_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setActiType(Integer actiType) {
		this.actiType = actiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Action.acti_describe
	 * @return  the value of Action.acti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getActiDescribe() {
		return actiDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Action.acti_describe
	 * @param actiDescribe  the value for Action.acti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setActiDescribe(String actiDescribe) {
		this.actiDescribe = actiDescribe;
	}
}