package com.swust.kelab.domain;

import java.util.Date;

public class BbsReply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer bbreId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_bbpo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer bbreBbpoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer bbreUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date bbreTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_hasattach
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean bbreHasattach;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BbsReply.bbre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String bbreContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_id
	 * @return  the value of BbsReply.bbre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getBbreId() {
		return bbreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_id
	 * @param bbreId  the value for BbsReply.bbre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreId(Integer bbreId) {
		this.bbreId = bbreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_bbpo_id
	 * @return  the value of BbsReply.bbre_bbpo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getBbreBbpoId() {
		return bbreBbpoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_bbpo_id
	 * @param bbreBbpoId  the value for BbsReply.bbre_bbpo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreBbpoId(Integer bbreBbpoId) {
		this.bbreBbpoId = bbreBbpoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_user_id
	 * @return  the value of BbsReply.bbre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getBbreUserId() {
		return bbreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_user_id
	 * @param bbreUserId  the value for BbsReply.bbre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreUserId(Integer bbreUserId) {
		this.bbreUserId = bbreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_time
	 * @return  the value of BbsReply.bbre_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getBbreTime() {
		return bbreTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_time
	 * @param bbreTime  the value for BbsReply.bbre_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreTime(Date bbreTime) {
		this.bbreTime = bbreTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_hasattach
	 * @return  the value of BbsReply.bbre_hasattach
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getBbreHasattach() {
		return bbreHasattach;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_hasattach
	 * @param bbreHasattach  the value for BbsReply.bbre_hasattach
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreHasattach(Boolean bbreHasattach) {
		this.bbreHasattach = bbreHasattach;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BbsReply.bbre_content
	 * @return  the value of BbsReply.bbre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getBbreContent() {
		return bbreContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BbsReply.bbre_content
	 * @param bbreContent  the value for BbsReply.bbre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setBbreContent(String bbreContent) {
		this.bbreContent = bbreContent;
	}
}