package com.swust.kelab.domain;

public class Clas {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Class.clas_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer clasId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Class.clas_grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer clasGradId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Class.clas_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String clasName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Class.clas_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String clasRemark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Class.clas_id
	 * @return  the value of Class.clas_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getClasId() {
		return clasId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Class.clas_id
	 * @param clasId  the value for Class.clas_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setClasId(Integer clasId) {
		this.clasId = clasId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Class.clas_grad_id
	 * @return  the value of Class.clas_grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getClasGradId() {
		return clasGradId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Class.clas_grad_id
	 * @param clasGradId  the value for Class.clas_grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setClasGradId(Integer clasGradId) {
		this.clasGradId = clasGradId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Class.clas_name
	 * @return  the value of Class.clas_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getClasName() {
		return clasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Class.clas_name
	 * @param clasName  the value for Class.clas_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setClasName(String clasName) {
		this.clasName = clasName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Class.clas_remark
	 * @return  the value of Class.clas_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getClasRemark() {
		return clasRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Class.clas_remark
	 * @param clasRemark  the value for Class.clas_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setClasRemark(String clasRemark) {
		this.clasRemark = clasRemark;
	}
}