package com.swust.kelab.domain;

public class ExamQuestionWithBLOBs extends ExamQuestion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String exquDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_correctanswer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String exquCorrectanswer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_describe
	 * @return  the value of ExamQuestion.exqu_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExquDescribe() {
		return exquDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_describe
	 * @param exquDescribe  the value for ExamQuestion.exqu_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquDescribe(String exquDescribe) {
		this.exquDescribe = exquDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_correctanswer
	 * @return  the value of ExamQuestion.exqu_correctanswer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExquCorrectanswer() {
		return exquCorrectanswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_correctanswer
	 * @param exquCorrectanswer  the value for ExamQuestion.exqu_correctanswer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquCorrectanswer(String exquCorrectanswer) {
		this.exquCorrectanswer = exquCorrectanswer;
	}
}