package com.swust.kelab.domain;

import java.util.Date;

public class ExamInformation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exinExpaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String exinName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_totaltime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exinTotaltime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date exinCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date exinBegintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date exinEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamInformation.exin_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String exinDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_id
	 * @return  the value of ExamInformation.exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExinId() {
		return exinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_id
	 * @param exinId  the value for ExamInformation.exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinId(Integer exinId) {
		this.exinId = exinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_expa_id
	 * @return  the value of ExamInformation.exin_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExinExpaId() {
		return exinExpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_expa_id
	 * @param exinExpaId  the value for ExamInformation.exin_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinExpaId(Integer exinExpaId) {
		this.exinExpaId = exinExpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_name
	 * @return  the value of ExamInformation.exin_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExinName() {
		return exinName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_name
	 * @param exinName  the value for ExamInformation.exin_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinName(String exinName) {
		this.exinName = exinName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_totaltime
	 * @return  the value of ExamInformation.exin_totaltime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExinTotaltime() {
		return exinTotaltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_totaltime
	 * @param exinTotaltime  the value for ExamInformation.exin_totaltime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinTotaltime(Integer exinTotaltime) {
		this.exinTotaltime = exinTotaltime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_createtime
	 * @return  the value of ExamInformation.exin_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getExinCreatetime() {
		return exinCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_createtime
	 * @param exinCreatetime  the value for ExamInformation.exin_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinCreatetime(Date exinCreatetime) {
		this.exinCreatetime = exinCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_begintime
	 * @return  the value of ExamInformation.exin_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getExinBegintime() {
		return exinBegintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_begintime
	 * @param exinBegintime  the value for ExamInformation.exin_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinBegintime(Date exinBegintime) {
		this.exinBegintime = exinBegintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_endtime
	 * @return  the value of ExamInformation.exin_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getExinEndtime() {
		return exinEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_endtime
	 * @param exinEndtime  the value for ExamInformation.exin_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinEndtime(Date exinEndtime) {
		this.exinEndtime = exinEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamInformation.exin_describe
	 * @return  the value of ExamInformation.exin_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExinDescribe() {
		return exinDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamInformation.exin_describe
	 * @param exinDescribe  the value for ExamInformation.exin_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExinDescribe(String exinDescribe) {
		this.exinDescribe = exinDescribe;
	}
}