package com.swust.kelab.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExamQuestion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exquId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exquCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exquType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date exquCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String exquCreateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer exquDifficulty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamQuestion.exqu_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean exquAttachment;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_id
	 * @return  the value of ExamQuestion.exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExquId() {
		return exquId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_id
	 * @param exquId  the value for ExamQuestion.exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquId(Integer exquId) {
		this.exquId = exquId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_cour_id
	 * @return  the value of ExamQuestion.exqu_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExquCourId() {
		return exquCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_cour_id
	 * @param exquCourId  the value for ExamQuestion.exqu_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquCourId(Integer exquCourId) {
		this.exquCourId = exquCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_type
	 * @return  the value of ExamQuestion.exqu_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExquType() {
		return exquType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_type
	 * @param exquType  the value for ExamQuestion.exqu_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquType(Integer exquType) {
		this.exquType = exquType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_createtime
	 * @return  the value of ExamQuestion.exqu_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getExquCreatetime() {
		return exquCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_createtime
	 * @param exquCreatetime  the value for ExamQuestion.exqu_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquCreatetime(Date exquCreatetime) {
		this.exquCreatetime = exquCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_create_userid
	 * @return  the value of ExamQuestion.exqu_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExquCreateUserid() {
		return exquCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_create_userid
	 * @param exquCreateUserid  the value for ExamQuestion.exqu_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquCreateUserid(String exquCreateUserid) {
		this.exquCreateUserid = exquCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_difficulty
	 * @return  the value of ExamQuestion.exqu_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExquDifficulty() {
		return exquDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_difficulty
	 * @param exquDifficulty  the value for ExamQuestion.exqu_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquDifficulty(Integer exquDifficulty) {
		this.exquDifficulty = exquDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamQuestion.exqu_attachment
	 * @return  the value of ExamQuestion.exqu_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getExquAttachment() {
		return exquAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamQuestion.exqu_attachment
	 * @param exquAttachment  the value for ExamQuestion.exqu_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExquAttachment(Boolean exquAttachment) {
		this.exquAttachment = exquAttachment;
	}

	private String exquDescribe;
	private String exquCorrectanswer;
	
	private List<Option> options = new ArrayList<Option>();
	public String getExquDescribe() {
		return exquDescribe;
	}

	public void setExquDescribe(String exquDescribe) {
		this.exquDescribe = exquDescribe;
	}

	public String getExquCorrectanswer() {
		return exquCorrectanswer;
	}

	public void setExquCorrectanswer(String exquCorrectanswer) {
		this.exquCorrectanswer = exquCorrectanswer;
	}

	public List<Option> getOptions() {
		return options;
	}

	public void setOptions(List<Option> options) {
		this.options = options;
	}
	
}