package com.swust.kelab.domain;

public class FunctionModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fumoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_parentid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fumoParentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String fumoName;
	
	
	private String fumoDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fumoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String fumoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fumoOrdinal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_id
	 * @return  the value of FunctionModel.fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	
	private String fumoIcon;
	
	public Integer getFumoId() {
		return fumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_id
	 * @param fumoId  the value for FunctionModel.fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoId(Integer fumoId) {
		this.fumoId = fumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_parentid
	 * @return  the value of FunctionModel.fumo_parentid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFumoParentid() {
		return fumoParentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_parentid
	 * @param fumoParentid  the value for FunctionModel.fumo_parentid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoParentid(Integer fumoParentid) {
		this.fumoParentid = fumoParentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_name
	 * @return  the value of FunctionModel.fumo_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getFumoName() {
		return fumoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_name
	 * @param fumoName  the value for FunctionModel.fumo_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoName(String fumoName) {
		this.fumoName = fumoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_type
	 * @return  the value of FunctionModel.fumo_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFumoType() {
		return fumoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_type
	 * @param fumoType  the value for FunctionModel.fumo_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoType(Integer fumoType) {
		this.fumoType = fumoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_url
	 * @return  the value of FunctionModel.fumo_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getFumoUrl() {
		return fumoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_url
	 * @param fumoUrl  the value for FunctionModel.fumo_url
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoUrl(String fumoUrl) {
		this.fumoUrl = fumoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_ordinal
	 * @return  the value of FunctionModel.fumo_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFumoOrdinal() {
		return fumoOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_ordinal
	 * @param fumoOrdinal  the value for FunctionModel.fumo_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoOrdinal(Integer fumoOrdinal) {
		this.fumoOrdinal = fumoOrdinal;
	}

	public String getFumoDescribe() {
		return fumoDescribe;
	}

	public void setFumoDescribe(String fumoDescribe) {
		this.fumoDescribe = fumoDescribe;
	}

	public String getFumoIcon() {
		return fumoIcon;
	}

	public void setFumoIcon(String fumoIcon) {
		this.fumoIcon = fumoIcon;
	}
}