package com.swust.kelab.domain;

public class FunctionAction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionAction.fuac_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fuacId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionAction.fuac_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fuacFumoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionAction.fuac_acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer fuacActiId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionAction.fuac_id
	 * @return  the value of FunctionAction.fuac_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFuacId() {
		return fuacId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionAction.fuac_id
	 * @param fuacId  the value for FunctionAction.fuac_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFuacId(Integer fuacId) {
		this.fuacId = fuacId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionAction.fuac_fumo_id
	 * @return  the value of FunctionAction.fuac_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFuacFumoId() {
		return fuacFumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionAction.fuac_fumo_id
	 * @param fuacFumoId  the value for FunctionAction.fuac_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFuacFumoId(Integer fuacFumoId) {
		this.fuacFumoId = fuacFumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionAction.fuac_acti_id
	 * @return  the value of FunctionAction.fuac_acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getFuacActiId() {
		return fuacActiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionAction.fuac_acti_id
	 * @param fuacActiId  the value for FunctionAction.fuac_acti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFuacActiId(Integer fuacActiId) {
		this.fuacActiId = fuacActiId;
	}
}