package com.swust.kelab.domain;

public class FunctionModelWithBLOBs extends FunctionModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String fumoDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FunctionModel.fumo_actions
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String fumoActions;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_describe
	 * @return  the value of FunctionModel.fumo_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getFumoDescribe() {
		return fumoDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_describe
	 * @param fumoDescribe  the value for FunctionModel.fumo_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoDescribe(String fumoDescribe) {
		this.fumoDescribe = fumoDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FunctionModel.fumo_actions
	 * @return  the value of FunctionModel.fumo_actions
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getFumoActions() {
		return fumoActions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FunctionModel.fumo_actions
	 * @param fumoActions  the value for FunctionModel.fumo_actions
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setFumoActions(String fumoActions) {
		this.fumoActions = fumoActions;
	}
}