package com.swust.kelab.domain;

public class Grade {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Grade.grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gradId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Grade.grad_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer gradDepaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Grade.grad_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String gradName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Grade.grad_id
	 * @return  the value of Grade.grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGradId() {
		return gradId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Grade.grad_id
	 * @param gradId  the value for Grade.grad_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGradId(Integer gradId) {
		this.gradId = gradId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Grade.grad_depa_id
	 * @return  the value of Grade.grad_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getGradDepaId() {
		return gradDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Grade.grad_depa_id
	 * @param gradDepaId  the value for Grade.grad_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGradDepaId(Integer gradDepaId) {
		this.gradDepaId = gradDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Grade.grad_name
	 * @return  the value of Grade.grad_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getGradName() {
		return gradName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Grade.grad_name
	 * @param gradName  the value for Grade.grad_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setGradName(String gradName) {
		this.gradName = gradName;
	}
}