package com.swust.kelab.domain;

public class HomepageColumnKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageColumn.hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer hocoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageColumn.hoco_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String hocoName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageColumn.hoco_id
	 * @return  the value of HomepageColumn.hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getHocoId() {
		return hocoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageColumn.hoco_id
	 * @param hocoId  the value for HomepageColumn.hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHocoId(Integer hocoId) {
		this.hocoId = hocoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageColumn.hoco_name
	 * @return  the value of HomepageColumn.hoco_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getHocoName() {
		return hocoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageColumn.hoco_name
	 * @param hocoName  the value for HomepageColumn.hoco_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHocoName(String hocoName) {
		this.hocoName = hocoName;
	}
}