package com.swust.kelab.domain;

import java.util.Date;

public class HomepageDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer hodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer hodeHocoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String hodeTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer hodeCreateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date hodeCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_change_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date hodeChangeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean hodeAttachment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageDetail.hode_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String hodeContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_id
	 * @return  the value of HomepageDetail.hode_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getHodeId() {
		return hodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_id
	 * @param hodeId  the value for HomepageDetail.hode_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeId(Integer hodeId) {
		this.hodeId = hodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_hoco_id
	 * @return  the value of HomepageDetail.hode_hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getHodeHocoId() {
		return hodeHocoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_hoco_id
	 * @param hodeHocoId  the value for HomepageDetail.hode_hoco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeHocoId(Integer hodeHocoId) {
		this.hodeHocoId = hodeHocoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_title
	 * @return  the value of HomepageDetail.hode_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getHodeTitle() {
		return hodeTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_title
	 * @param hodeTitle  the value for HomepageDetail.hode_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeTitle(String hodeTitle) {
		this.hodeTitle = hodeTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_create_userid
	 * @return  the value of HomepageDetail.hode_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getHodeCreateUserid() {
		return hodeCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_create_userid
	 * @param hodeCreateUserid  the value for HomepageDetail.hode_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeCreateUserid(Integer hodeCreateUserid) {
		this.hodeCreateUserid = hodeCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_create_time
	 * @return  the value of HomepageDetail.hode_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getHodeCreateTime() {
		return hodeCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_create_time
	 * @param hodeCreateTime  the value for HomepageDetail.hode_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeCreateTime(Date hodeCreateTime) {
		this.hodeCreateTime = hodeCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_change_time
	 * @return  the value of HomepageDetail.hode_change_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getHodeChangeTime() {
		return hodeChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_change_time
	 * @param hodeChangeTime  the value for HomepageDetail.hode_change_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeChangeTime(Date hodeChangeTime) {
		this.hodeChangeTime = hodeChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_attachment
	 * @return  the value of HomepageDetail.hode_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getHodeAttachment() {
		return hodeAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_attachment
	 * @param hodeAttachment  the value for HomepageDetail.hode_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeAttachment(Boolean hodeAttachment) {
		this.hodeAttachment = hodeAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageDetail.hode_content
	 * @return  the value of HomepageDetail.hode_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getHodeContent() {
		return hodeContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageDetail.hode_content
	 * @param hodeContent  the value for HomepageDetail.hode_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHodeContent(String hodeContent) {
		this.hodeContent = hodeContent;
	}
}