package com.swust.kelab.domain;

import java.util.Date;

public class HomepageColumn extends HomepageColumnKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageColumn.hoco_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer hocoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageColumn.hoco_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date hocoCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column HomepageColumn.hoco_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String hocoDescirbe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageColumn.hoco_type
	 * @return  the value of HomepageColumn.hoco_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getHocoType() {
		return hocoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageColumn.hoco_type
	 * @param hocoType  the value for HomepageColumn.hoco_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHocoType(Integer hocoType) {
		this.hocoType = hocoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageColumn.hoco_createtime
	 * @return  the value of HomepageColumn.hoco_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getHocoCreatetime() {
		return hocoCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageColumn.hoco_createtime
	 * @param hocoCreatetime  the value for HomepageColumn.hoco_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHocoCreatetime(Date hocoCreatetime) {
		this.hocoCreatetime = hocoCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column HomepageColumn.hoco_descirbe
	 * @return  the value of HomepageColumn.hoco_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getHocoDescirbe() {
		return hocoDescirbe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column HomepageColumn.hoco_descirbe
	 * @param hocoDescirbe  the value for HomepageColumn.hoco_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setHocoDescirbe(String hocoDescirbe) {
		this.hocoDescirbe = hocoDescirbe;
	}
}