package com.swust.kelab.domain;

import java.util.Date;

public class LearnProcessRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer lpreId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer lpreUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer lpreChapId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date lpreBegintime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date lpreEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_learntime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer lpreLearntime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LearnProcessRecord.lpre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String lpreContent;
	
	private Integer lpreResoId;

	public Integer getLpreResoId() {
		return lpreResoId;
	}

	public void setLpreResoId(Integer lpreResoId) {
		this.lpreResoId = lpreResoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_id
	 * @return  the value of LearnProcessRecord.lpre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLpreId() {
		return lpreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_id
	 * @param lpreId  the value for LearnProcessRecord.lpre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreId(Integer lpreId) {
		this.lpreId = lpreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_user_id
	 * @return  the value of LearnProcessRecord.lpre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLpreUserId() {
		return lpreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_user_id
	 * @param lpreUserId  the value for LearnProcessRecord.lpre_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreUserId(Integer lpreUserId) {
		this.lpreUserId = lpreUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_chap_id
	 * @return  the value of LearnProcessRecord.lpre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLpreChapId() {
		return lpreChapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_chap_id
	 * @param lpreChapId  the value for LearnProcessRecord.lpre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreChapId(Integer lpreChapId) {
		this.lpreChapId = lpreChapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_begintime
	 * @return  the value of LearnProcessRecord.lpre_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getLpreBegintime() {
		return lpreBegintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_begintime
	 * @param lpreBegintime  the value for LearnProcessRecord.lpre_begintime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreBegintime(Date lpreBegintime) {
		this.lpreBegintime = lpreBegintime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_endtime
	 * @return  the value of LearnProcessRecord.lpre_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getLpreEndtime() {
		return lpreEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_endtime
	 * @param lpreEndtime  the value for LearnProcessRecord.lpre_endtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreEndtime(Date lpreEndtime) {
		this.lpreEndtime = lpreEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_learntime
	 * @return  the value of LearnProcessRecord.lpre_learntime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLpreLearntime() {
		return lpreLearntime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_learntime
	 * @param lpreLearntime  the value for LearnProcessRecord.lpre_learntime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreLearntime(Integer lpreLearntime) {
		this.lpreLearntime = lpreLearntime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LearnProcessRecord.lpre_content
	 * @return  the value of LearnProcessRecord.lpre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getLpreContent() {
		return lpreContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LearnProcessRecord.lpre_content
	 * @param lpreContent  the value for LearnProcessRecord.lpre_content
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLpreContent(String lpreContent) {
		this.lpreContent = lpreContent;
	}

}