package com.swust.kelab.domain;

import java.util.Date;

public class Log {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer logUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date logTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_ip
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String logIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_client
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String logClient;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer logType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column log.log_opt
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String logOpt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_id
	 * @return  the value of log.log_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_id
	 * @param logId  the value for log.log_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_user_id
	 * @return  the value of log.log_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLogUserId() {
		return logUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_user_id
	 * @param logUserId  the value for log.log_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogUserId(Integer logUserId) {
		this.logUserId = logUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_time
	 * @return  the value of log.log_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getLogTime() {
		return logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_time
	 * @param logTime  the value for log.log_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_ip
	 * @return  the value of log.log_ip
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getLogIp() {
		return logIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_ip
	 * @param logIp  the value for log.log_ip
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogIp(String logIp) {
		this.logIp = logIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_client
	 * @return  the value of log.log_client
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getLogClient() {
		return logClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_client
	 * @param logClient  the value for log.log_client
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogClient(String logClient) {
		this.logClient = logClient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_type
	 * @return  the value of log.log_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getLogType() {
		return logType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_type
	 * @param logType  the value for log.log_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogType(Integer logType) {
		this.logType = logType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column log.log_opt
	 * @return  the value of log.log_opt
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getLogOpt() {
		return logOpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column log.log_opt
	 * @param logOpt  the value for log.log_opt
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setLogOpt(String logOpt) {
		this.logOpt = logOpt;
	}
}