package com.swust.kelab.domain;

import java.util.Date;

public class MassedLearning {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleResoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String maleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date maleCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_startTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date maleStarttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_duration
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date maleEndTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_schoolId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleSchoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_teacherId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleTeacherid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer maleState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearning.male_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String maleDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_id
	 * @return  the value of MassedLearning.male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleId() {
		return maleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_id
	 * @param maleId  the value for MassedLearning.male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleId(Integer maleId) {
		this.maleId = maleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_cour_id
	 * @return  the value of MassedLearning.male_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleCourId() {
		return maleCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_cour_id
	 * @param maleCourId  the value for MassedLearning.male_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleCourId(Integer maleCourId) {
		this.maleCourId = maleCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_reso_id
	 * @return  the value of MassedLearning.male_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleResoId() {
		return maleResoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_reso_id
	 * @param maleResoId  the value for MassedLearning.male_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleResoId(Integer maleResoId) {
		this.maleResoId = maleResoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_name
	 * @return  the value of MassedLearning.male_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getMaleName() {
		return maleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_name
	 * @param maleName  the value for MassedLearning.male_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleName(String maleName) {
		this.maleName = maleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_createTime
	 * @return  the value of MassedLearning.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getMaleCreatetime() {
		return maleCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_createTime
	 * @param maleCreatetime  the value for MassedLearning.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleCreatetime(Date maleCreatetime) {
		this.maleCreatetime = maleCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_startTime
	 * @return  the value of MassedLearning.male_startTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getMaleStarttime() {
		return maleStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_startTime
	 * @param maleStarttime  the value for MassedLearning.male_startTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleStarttime(Date maleStarttime) {
		this.maleStarttime = maleStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_duration
	 * @return  the value of MassedLearning.male_duration
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getMaleEndTime() {
		return maleEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_duration
	 * @param maleDuration  the value for MassedLearning.male_duration
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleEndTime(Date maleEndTime) {
		this.maleEndTime = maleEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_schoolId
	 * @return  the value of MassedLearning.male_schoolId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleSchoolid() {
		return maleSchoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_schoolId
	 * @param maleSchoolid  the value for MassedLearning.male_schoolId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleSchoolid(Integer maleSchoolid) {
		this.maleSchoolid = maleSchoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_teacherId
	 * @return  the value of MassedLearning.male_teacherId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleTeacherid() {
		return maleTeacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_teacherId
	 * @param maleTeacherid  the value for MassedLearning.male_teacherId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleTeacherid(Integer maleTeacherid) {
		this.maleTeacherid = maleTeacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_state
	 * @return  the value of MassedLearning.male_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMaleState() {
		return maleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_state
	 * @param maleState  the value for MassedLearning.male_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleState(Integer maleState) {
		this.maleState = maleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearning.male_describe
	 * @return  the value of MassedLearning.male_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getMaleDescribe() {
		return maleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearning.male_describe
	 * @param maleDescribe  the value for MassedLearning.male_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleDescribe(String maleDescribe) {
		this.maleDescribe = maleDescribe;
	}
}