package com.swust.kelab.domain;

import java.util.Date;

public class MassedLearningManage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearningManage.mlma_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer mlmaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearningManage.mlma_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer mlmaCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearningManage.mlma_maxTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer mlmaMaxtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearningManage.mala_maxStudentNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer malaMaxstudentnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MassedLearningManage.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date maleCreatetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearningManage.mlma_id
	 * @return  the value of MassedLearningManage.mlma_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMlmaId() {
		return mlmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearningManage.mlma_id
	 * @param mlmaId  the value for MassedLearningManage.mlma_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMlmaId(Integer mlmaId) {
		this.mlmaId = mlmaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearningManage.mlma_cour_id
	 * @return  the value of MassedLearningManage.mlma_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMlmaCourId() {
		return mlmaCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearningManage.mlma_cour_id
	 * @param mlmaCourId  the value for MassedLearningManage.mlma_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMlmaCourId(Integer mlmaCourId) {
		this.mlmaCourId = mlmaCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearningManage.mlma_maxTime
	 * @return  the value of MassedLearningManage.mlma_maxTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMlmaMaxtime() {
		return mlmaMaxtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearningManage.mlma_maxTime
	 * @param mlmaMaxtime  the value for MassedLearningManage.mlma_maxTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMlmaMaxtime(Integer mlmaMaxtime) {
		this.mlmaMaxtime = mlmaMaxtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearningManage.mala_maxStudentNum
	 * @return  the value of MassedLearningManage.mala_maxStudentNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getMalaMaxstudentnum() {
		return malaMaxstudentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearningManage.mala_maxStudentNum
	 * @param malaMaxstudentnum  the value for MassedLearningManage.mala_maxStudentNum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMalaMaxstudentnum(Integer malaMaxstudentnum) {
		this.malaMaxstudentnum = malaMaxstudentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MassedLearningManage.male_createTime
	 * @return  the value of MassedLearningManage.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getMaleCreatetime() {
		return maleCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MassedLearningManage.male_createTime
	 * @param maleCreatetime  the value for MassedLearningManage.male_createTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setMaleCreatetime(Date maleCreatetime) {
		this.maleCreatetime = maleCreatetime;
	}
}