package com.swust.kelab.domain;

import java.util.Date;

public class ReAuthority {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_Authority.reau_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reauId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_Authority.reau_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reauRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_Authority.reau_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reauFumoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_Authority.reau_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date reauCreatetime;

	
	private String reauActions;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_Authority.reau_id
	 * @return  the value of Re_Authority.reau_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReauId() {
		return reauId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_Authority.reau_id
	 * @param reauId  the value for Re_Authority.reau_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReauId(Integer reauId) {
		this.reauId = reauId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_Authority.reau_role_id
	 * @return  the value of Re_Authority.reau_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReauRoleId() {
		return reauRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_Authority.reau_role_id
	 * @param reauRoleId  the value for Re_Authority.reau_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReauRoleId(Integer reauRoleId) {
		this.reauRoleId = reauRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_Authority.reau_fumo_id
	 * @return  the value of Re_Authority.reau_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReauFumoId() {
		return reauFumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_Authority.reau_fumo_id
	 * @param reauFumoId  the value for Re_Authority.reau_fumo_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReauFumoId(Integer reauFumoId) {
		this.reauFumoId = reauFumoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_Authority.reau_createtime
	 * @return  the value of Re_Authority.reau_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getReauCreatetime() {
		return reauCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_Authority.reau_createtime
	 * @param reauCreatetime  the value for Re_Authority.reau_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReauCreatetime(Date reauCreatetime) {
		this.reauCreatetime = reauCreatetime;
	}

	public String getReauActions() {
		return reauActions;
	}

	public void setReauActions(String reauActions) {
		this.reauActions = reauActions;
	}
}