package com.swust.kelab.domain;

public class ReChapterResource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_ChapterResource.rcre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rcreId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_ChapterResource.rcre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rcreChapId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_ChapterResource.rcre_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rcreResoId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_ChapterResource.rcre_id
	 * @return  the value of Re_ChapterResource.rcre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRcreId() {
		return rcreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_ChapterResource.rcre_id
	 * @param rcreId  the value for Re_ChapterResource.rcre_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRcreId(Integer rcreId) {
		this.rcreId = rcreId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_ChapterResource.rcre_chap_id
	 * @return  the value of Re_ChapterResource.rcre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRcreChapId() {
		return rcreChapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_ChapterResource.rcre_chap_id
	 * @param rcreChapId  the value for Re_ChapterResource.rcre_chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRcreChapId(Integer rcreChapId) {
		this.rcreChapId = rcreChapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_ChapterResource.rcre_reso_id
	 * @return  the value of Re_ChapterResource.rcre_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRcreResoId() {
		return rcreResoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_ChapterResource.rcre_reso_id
	 * @param rcreResoId  the value for Re_ChapterResource.rcre_reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRcreResoId(Integer rcreResoId) {
		this.rcreResoId = rcreResoId;
	}
}