package com.swust.kelab.domain;

public class ReGroupPaper {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_GroupPaper.rgpa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rgpaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_GroupPaper.rgpa_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rgpaExpaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_GroupPaper.rgpa_exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rgpaExquId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_GroupPaper.rgpa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rgpaOrdinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_GroupPaper.rgpa_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rgpaScore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_GroupPaper.rgpa_id
	 * @return  the value of Re_GroupPaper.rgpa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRgpaId() {
		return rgpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_GroupPaper.rgpa_id
	 * @param rgpaId  the value for Re_GroupPaper.rgpa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRgpaId(Integer rgpaId) {
		this.rgpaId = rgpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_GroupPaper.rgpa_expa_id
	 * @return  the value of Re_GroupPaper.rgpa_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRgpaExpaId() {
		return rgpaExpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_GroupPaper.rgpa_expa_id
	 * @param rgpaExpaId  the value for Re_GroupPaper.rgpa_expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRgpaExpaId(Integer rgpaExpaId) {
		this.rgpaExpaId = rgpaExpaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_GroupPaper.rgpa_exqu_id
	 * @return  the value of Re_GroupPaper.rgpa_exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRgpaExquId() {
		return rgpaExquId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_GroupPaper.rgpa_exqu_id
	 * @param rgpaExquId  the value for Re_GroupPaper.rgpa_exqu_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRgpaExquId(Integer rgpaExquId) {
		this.rgpaExquId = rgpaExquId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_GroupPaper.rgpa_ordinal
	 * @return  the value of Re_GroupPaper.rgpa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRgpaOrdinal() {
		return rgpaOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_GroupPaper.rgpa_ordinal
	 * @param rgpaOrdinal  the value for Re_GroupPaper.rgpa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRgpaOrdinal(Integer rgpaOrdinal) {
		this.rgpaOrdinal = rgpaOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_GroupPaper.rgpa_score
	 * @return  the value of Re_GroupPaper.rgpa_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRgpaScore() {
		return rgpaScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_GroupPaper.rgpa_score
	 * @param rgpaScore  the value for Re_GroupPaper.rgpa_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRgpaScore(Float rgpaScore) {
		this.rgpaScore = rgpaScore;
	}
}