package com.swust.kelab.domain;

import java.util.Date;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String resoTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String resoLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String resoFilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_addtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date resoAddtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoDownnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_share
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean resoShare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_vedioTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer resoVediotime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Resource.reso_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String resoDescribe;
	
	/**	
	 * 视频当前的状态
	 * 1. 正常	2. 删除	3. 拷贝未完成
	 */
	private Integer resoStatus; 
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_id
	 * @return  the value of Resource.reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoId() {
		return resoId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_id
	 * @param resoId  the value for Resource.reso_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoId(Integer resoId) {
		this.resoId = resoId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_cour_id
	 * @return  the value of Resource.reso_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoCourId() {
		return resoCourId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_cour_id
	 * @param resoCourId  the value for Resource.reso_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoCourId(Integer resoCourId) {
		this.resoCourId = resoCourId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_type
	 * @return  the value of Resource.reso_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoType() {
		return resoType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_type
	 * @param resoType  the value for Resource.reso_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoType(Integer resoType) {
		this.resoType = resoType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_title
	 * @return  the value of Resource.reso_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getResoTitle() {
		return resoTitle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_title
	 * @param resoTitle  the value for Resource.reso_title
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoTitle(String resoTitle) {
		this.resoTitle = resoTitle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_location
	 * @return  the value of Resource.reso_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getResoLocation() {
		return resoLocation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_location
	 * @param resoLocation  the value for Resource.reso_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoLocation(String resoLocation) {
		this.resoLocation = resoLocation;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_filename
	 * @return  the value of Resource.reso_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getResoFilename() {
		return resoFilename;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_filename
	 * @param resoFilename  the value for Resource.reso_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoFilename(String resoFilename) {
		this.resoFilename = resoFilename;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_userid
	 * @return  the value of Resource.reso_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoUserid() {
		return resoUserid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_userid
	 * @param resoUserid  the value for Resource.reso_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoUserid(Integer resoUserid) {
		this.resoUserid = resoUserid;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_addtime
	 * @return  the value of Resource.reso_addtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getResoAddtime() {
		return resoAddtime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_addtime
	 * @param resoAddtime  the value for Resource.reso_addtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoAddtime(Date resoAddtime) {
		this.resoAddtime = resoAddtime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_downnum
	 * @return  the value of Resource.reso_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoDownnum() {
		return resoDownnum;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_downnum
	 * @param resoDownnum  the value for Resource.reso_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoDownnum(Integer resoDownnum) {
		this.resoDownnum = resoDownnum;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_share
	 * @return  the value of Resource.reso_share
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getResoShare() {
		return resoShare;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_share
	 * @param resoShare  the value for Resource.reso_share
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoShare(Boolean resoShare) {
		this.resoShare = resoShare;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_vedioTime
	 * @return  the value of Resource.reso_vedioTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getResoVediotime() {
		return resoVediotime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_vedioTime
	 * @param resoVediotime  the value for Resource.reso_vedioTime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoVediotime(Integer resoVediotime) {
		this.resoVediotime = resoVediotime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Resource.reso_describe
	 * @return  the value of Resource.reso_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getResoDescribe() {
		return resoDescribe;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Resource.reso_describe
	 * @param resoDescribe  the value for Resource.reso_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setResoDescribe(String resoDescribe) {
		this.resoDescribe = resoDescribe;
	}
	public Integer getResoStatus() {
		return resoStatus;
	}
	public void setResoStatus(Integer resoStatus) {
		this.resoStatus = resoStatus;
	}
	public final static int LINK = 1;
	public final static int DOCUMENT = 2;
	public final static int VEDIO = 3;
}