package com.swust.kelab.domain;

public class StudentMassedLearning {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StudentMassedLearning.smle_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer smleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StudentMassedLearning.smle_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer smleUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StudentMassedLearning.smle_male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer smleMaleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StudentMassedLearning.smle_id
	 * @return  the value of StudentMassedLearning.smle_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSmleId() {
		return smleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StudentMassedLearning.smle_id
	 * @param smleId  the value for StudentMassedLearning.smle_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSmleId(Integer smleId) {
		this.smleId = smleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StudentMassedLearning.smle_user_id
	 * @return  the value of StudentMassedLearning.smle_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSmleUserId() {
		return smleUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StudentMassedLearning.smle_user_id
	 * @param smleUserId  the value for StudentMassedLearning.smle_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSmleUserId(Integer smleUserId) {
		this.smleUserId = smleUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StudentMassedLearning.smle_male_id
	 * @return  the value of StudentMassedLearning.smle_male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSmleMaleId() {
		return smleMaleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StudentMassedLearning.smle_male_id
	 * @param smleMaleId  the value for StudentMassedLearning.smle_male_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSmleMaleId(Integer smleMaleId) {
		this.smleMaleId = smleMaleId;
	}
}