package com.swust.kelab.domain;

public class SystemParameter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SystemParameter.sypa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer sypaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SystemParameter.sypa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String sypaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SystemParameter.sypa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer sypaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SystemParameter.sypa_value
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String sypaValue;
	/**
	 * 参数备注
	 */
	private String sypaRemark;
	/**
	 * 参数英文名
	 */
	private String sypaEnName;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SystemParameter.sypa_id
	 * @return  the value of SystemParameter.sypa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSypaId() {
		return sypaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SystemParameter.sypa_id
	 * @param sypaId  the value for SystemParameter.sypa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSypaId(Integer sypaId) {
		this.sypaId = sypaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SystemParameter.sypa_name
	 * @return  the value of SystemParameter.sypa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getSypaName() {
		return sypaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SystemParameter.sypa_name
	 * @param sypaName  the value for SystemParameter.sypa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSypaName(String sypaName) {
		this.sypaName = sypaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SystemParameter.sypa_type
	 * @return  the value of SystemParameter.sypa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSypaType() {
		return sypaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SystemParameter.sypa_type
	 * @param sypaType  the value for SystemParameter.sypa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSypaType(Integer sypaType) {
		this.sypaType = sypaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SystemParameter.sypa_value
	 * @return  the value of SystemParameter.sypa_value
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getSypaValue() {
		return sypaValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SystemParameter.sypa_value
	 * @param sypaValue  the value for SystemParameter.sypa_value
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSypaValue(String sypaValue) {
		this.sypaValue = sypaValue;
	}

    public String getSypaRemark() {
        return sypaRemark;
    }

    public void setSypaRemark(String sypaRemark) {
        this.sypaRemark = sypaRemark;
    }

    public String getSypaEnName() {
        return sypaEnName;
    }

    public void setSypaEnName(String sypaEnName) {
        this.sypaEnName = sypaEnName;
    }
	
}