package com.swust.kelab.domain;

public class VedioServer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer veseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String veseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_ip
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String veseLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer veseDepaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer veseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer veseState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VedioServer.vese_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String veseRemark;
	/**
	 * 标识服务器是否被使用
	 */
	private  int veseEnable; 
	/**
	 * 登录用户名
	 */
	private String veseLoginName;
	/**
	 * 登录密码
	 */
	private String vesePassword;
	/**
	 * 内网ip
	 */
	private String veseInnerIp;
	/**
	 * 外网ip
	 */
	private String veseOuterIp;
	/**
	 * 内网掩码
	 */
	private String veseInnerMask;
	/**
	 * 外网掩码
	 */
	private String veseOuterMask;
	
 
	/**
	 * 
	 * 
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_id
	 * @return  the value of VedioServer.vese_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getVeseId() {
		return veseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_id
	 * @param veseId  the value for VedioServer.vese_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseId(Integer veseId) {
		this.veseId = veseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_name
	 * @return  the value of VedioServer.vese_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getVeseName() {
		return veseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_name
	 * @param veseName  the value for VedioServer.vese_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseName(String veseName) {
		this.veseName = veseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_location
	 * @return  the value of VedioServer.vese_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getVeseLocation() {
		return veseLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_location
	 * @param veseLocation  the value for VedioServer.vese_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseLocation(String veseLocation) {
		this.veseLocation = veseLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_depa_id
	 * @return  the value of VedioServer.vese_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getVeseDepaId() {
		return veseDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_depa_id
	 * @param veseDepaId  the value for VedioServer.vese_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseDepaId(Integer veseDepaId) {
		this.veseDepaId = veseDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_type
	 * @return  the value of VedioServer.vese_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getVeseType() {
		return veseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_type
	 * @param veseType  the value for VedioServer.vese_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseType(Integer veseType) {
		this.veseType = veseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_state
	 * @return  the value of VedioServer.vese_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getVeseState() {
		return veseState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_state
	 * @param veseState  the value for VedioServer.vese_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseState(Integer veseState) {
		this.veseState = veseState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VedioServer.vese_remark
	 * @return  the value of VedioServer.vese_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getVeseRemark() {
		return veseRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VedioServer.vese_remark
	 * @param veseRemark  the value for VedioServer.vese_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setVeseRemark(String veseRemark) {
		this.veseRemark = veseRemark;
	}

    public int getVeseEnable() {
        return veseEnable;
    }

    public void setVeseEnable(int veseEnable) {
        this.veseEnable = veseEnable;
    }

    public String getVeseLoginName() {
        return veseLoginName;
    }

    public void setVeseLoginName(String veseLoginName) {
        this.veseLoginName = veseLoginName;
    }

    public String getVesePassword() {
        return vesePassword;
    }

    public void setVesePassword(String vesePassword) {
        this.vesePassword = vesePassword;
    }

	public String getVeseInnerIp() {
		return veseInnerIp;
	}

	public void setVeseInnerIp(String veseInnerIp) {
		this.veseInnerIp = veseInnerIp;
	}

	public String getVeseOuterIp() {
		return veseOuterIp;
	}

	public void setVeseOuterIp(String veseOuterIp) {
		this.veseOuterIp = veseOuterIp;
	}

	public String getVeseInnerMask() {
		return veseInnerMask;
	}

	public void setVeseInnerMask(String veseInnerMask) {
		this.veseInnerMask = veseInnerMask;
	}

	public String getVeseOuterMask() {
		return veseOuterMask;
	}

	public void setVeseOuterMask(String veseOuterMask) {
		this.veseOuterMask = veseOuterMask;
	}
 
}